version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      Y/ZjUCgwCRNSRj2xcxOlRcWLB9BW2NpUCBSQAXuOyeuM28zjPUk2IlA8s8sN79UG9uWQ3XcOBbDqorae1E34Hfsonomf4rZXrd1TMDmsv+S17Gwnw8dv2Pee2mfFS5jzgabknqssgsXVhznM3MWHB0mP0MA5u8tuGTdZH/hFbgievvUPyfgM93q6XdWdu8euN77ySotyQhI/QLqHSKe0VzzRlvu/8xJw+QWk8jSXyizF47lUdrR62DMYASmYGLgrfhog3zK48B8DbA4KhCcmfLKGjw/CcPm3teV5Z5md0LPw+3FSI4DPchov/lblzfYPj8Ubg00QGj0qkI6QGevUpffAnzEPIkQ7+EtYWS/SCZm1ePOEayWZPgM6Y9d8Vqrm/8G/yXTU649PrX3oRpHANzTDaXxTAYHj6Xvs3x1rCOKGIdd/d30YuuHbzXTttEiFfOMJDGRqw+4WdZDOWcLo10kd8L+7iQ953/vSkqghtwjICgwq9klxCmZnN3PfS4XGbE2geRv304EGa6ri5svpyzENVM/ukMC40ZuWox6ntaUEKxEdMeCX5o8TVEaoz9vxiNjUaghSmwAx0eeM6A/kcKToSgmm6Y8Q0QH03GXm+m/iX4LeBIzefNUrbqjctSup77STvT6onFWj15UfV1+tFyYlbZMWX0Tns//DXmU1RXs=
