version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      T6jTY8KylBay8XwehUiZgAoem2Uo1pMq1ksWISQpFUsJNHcjopQG/UrhPcwUVWxg230jWQqi+udmTDJodr+p3O3VjXEpRJbOPT1EB2K8Lg0DPXdx06R3I70xR4VlnQsKgP51rTWv/FB6x3LAkOEHq/4rnw9ieJy7Hm2sS2Ttmglqg/4L4FQ6aThGvBgGIrtTyiIAwFEj0XyFnvKuQKe5t6JRIKBZMaf/bjdtCe6ddVZ8vckvmYOFV+ApxEQf4LZb+A9pk42fKIZJqJm5kzXMME9GRYoOT9be1sNAFsaQTtrFyGaIePTb3sHH13WymvLhNSSlqK1Zmq1mGQ07gosC8BaThAxZ6gj3fPem1c7vc4NvFM0J+WGw1t8KMY7XFFW1ltfkAlhOhlK06kNoH6FfBFU0pU6AQDji5ueJvXm7PwaYPCfSjlMjME10CpGFfpJKqTxuAn1SVt2BxzO/Fg1rJy8L/gHtK9P+MNeRazF/K0mVxgvWTG7qd8QOplYJz90d2sYVgk53TkJgR60A+/X5ZsP1+xxQVpPZNXuWiKJK5hC2iWWXX+VJBvUI1I3kIKYPXQB2AsBMkgqOWyhOQ/s2JXkMJGrA5lKexJfDlT5dbUs7MGIMz0VnV2127FYZ257siVD1Jt6xc2WQQyxoT5fvsVI2i8Xv6nC3xmMYkBGLtwU=
